### ISSUE TITLE
M3U8_Playlist(url) raises InvalidPathM3U8 exception when URL contains query parameters

### ISSUE THREAD

**Issue by Zhen-Bo** [olivialba/M3U8-to-MP4#2]
## Description

I encountered an issue when using the `M3U8_Playlist(f"URL:{url}")` function. If the `url` contains query parameters, it raises an `m3u8_to_mp4.exceptions.InvalidPathM3U8` exception.

## Steps to Reproduce

1. Use a URL that contains query parameters, for example: `https://example.com/playlist.m3u8?token=abc123`
2. Call the `M3U8_Playlist(f"URL:{url}")` function with the URL.

```python
from m3u8_to_mp4.m3u8 import M3U8_Playlist


def download_m3u8(url, output_path):
    stream = M3U8_Playlist(f"URL:{url}")
    stream.setHeaders(
        {
            "Referer": "https://rplay.live",
            "Origin": "https://rplay.live",
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
            ),
        }
    )
    stream.to_mp4(destination=output_path, delete_after=True)
```

error:
```
Exception in thread Thread-8 (download_m3u8):
Traceback (most recent call last):
  File "D:\Program Files\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Admin\Desktop\WORKSPACE\rPlay\Lib\download_m3u8.py", line 5, in download_m3u8
    stream = M3U8_Playlist(f"URL:{url}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Admin\Desktop\WORKSPACE\rPlay\.venv\Lib\site-packages\m3u8_to_mp4\m3u8.py", line 28, in __init__
    self.__get_m3u8(path) 
    ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Admin\Desktop\WORKSPACE\rPlay\.venv\Lib\site-packages\m3u8_to_mp4\m3u8.py", line 126, in __get_m3u8
    raise InvalidUrlM3U8
m3u8_to_mp4.exceptions.InvalidUrlM3U8
```

**Comment by Zhen-Bo** [comment]
I apologize for not realizing that my m3u8 URL was returning a 404 error, which led to my misunderstanding.
